<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td align="center" height="10" colspan="2">
			<h1>Stránky o tom jak je fajné lyžování mimo sjezdofky a jiné kraviny.</h1>
		</td>
	</tr>

	<tr>
		<td valign="top" align="left">
			<table border="0" width="100%" cellpadding="0" cellspacing="0">
				<tr>
					<td align="left">
						<?php /* TODO - dynamicaly generated menu */ ?>
						<table border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td class="menu" valign="top" width="110">
									<span>
										<a id="about_us" href="aboutus" alt="O nás"></a>
									</span>
									<span>
										<a id="terrains" href="terrains" alt="Terény"></a>
									</span>
									<span>
										<a id="video" href="video" alt="Video"></a>
									</span>										
									<span>
										<a id="chat" href="chat" alt="Pokec"></a>
									</span>	
									<span>
										<a id="links" href="links" alt="Odkazy"></a>
									</span>
								</td> 
								<td width="390" valign="top" align="center">
									<a href="uf"><img src="images/page/uf.jpg" width="390" height="230" border="0" alt="Blbosti"></a>
								</td>
							</tr>
						</table>
					</td>
					<?php /* TODO - change to dynamically generated list of articles */ ?>
					<td valign="top" align="center" width="200"><h5>
							<a href="article/view?id=67">Špind,finále eBanka cupu</a><br>
							<a href="article/view?id=58">fotky východu slunce</a><br>
							<a href="article/view?id=48">la norma 02</a><br>
							<a href="article/view?id=47">fryrajd na ropici</a><br>
							<a href="article/view?id=46">snowpark na horní bečvě</a><br>
							<a href="article/view?id=45">tatry v květnu</a><br>
							<a href="article/view?id=44">bratislavská halda</a><br>
							<a href="article/view?id=50">robin v les sybelles 2001</a><br>
							<a href="article/view?id=49">verbier 01</a><br>
							<a href="video/">videa ze skishow</a></h5>
					</td>
				</tr>
			</table> 
		</td>
	</tr>

	<tr>
		<td valign="bottom" width="100%">
			<table border="0" width="100%">
				<tr>
					<td width="200" valign="bottom" align="left">
						<div class="mno" align="left">Dnešní datum: <?= date("j.m.Y") /* require('asfasdf.php') */ ?></div>
						<div class="mno" align="left">Aktualizováno: 7.12.2014</div>
					</td>
					<td>    
					</td>
					<td width="200">
					</td>
				</tr>
			</table>

	<tr>
		<td valign="bottom" align="center">
			<hr width="90%">
			<div class="hel9"> Pokud budete mít neodbytnou potřebu mi něco napsat, pište na adresu <a href=mailto:banix@centrum.cz>banix@centrum.cz</a></div>
		</td>
	</tr>
</table>