<?php
	$portrait = 'banik.gif';
	$auser = 'Banik';
?>

<table border=0 align="right">
	<tr>
		<td align=center>
			<table bgcolor="white" cellpadding=0 cellspacing=0 border=1>
				<tr>
					<td>
						<img src="<?= $this->baseUrl()?>/images/ports/<?= $portrait?>" border=0>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align=center>
			<font face="helvetica"><b><?= $auser?></b></font>
		</td>
	</tr>
	<tr>
		<td align=center>
			<font face="helvetica"><b><?= date('j.m.Y')?></b></font>
		</td>
	</tr>
	<tr>
		<td align="center"><a href="<?= $this->baseUrl()?>/chat/logout">Odhlásit</a>
		</td>
	</tr>
	<tr>
		<td align="center"><a href="<?= $this->baseUrl()?>/chat/edit">Editovat</a>
		</td>
	</tr>
</table>