<?php
$this->title = 'Terény';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td align=center valign=middle>
			<a href="terrains/ropice"><img src="images/page/terrop.jpg" border="0" alt="Ropice"></a>
			<a href="terrains/lysa"><img src="images/page/terlys.jpg" border="0" alt="Lysá hora"></a>
			<a href="terrains/tatry"><img src="images/page/tertat.jpg" border="0" alt="Vysoké Tatry"></a>
			<a href="terrains/valthorens"><img src="images/page/tervt.jpg" border="0" alt="Val Thorens"></a>
			<a href="terrains/lda"><img src="images/page/terlda.jpg" border="0" alt="Les Deux Alpes"></a>
			<a href="terrains/cham"><img src="images/page/tercham.jpg" border="0" alt="Chamonix"></a>
			<a href="terrains/other"><img src="images/page/terother.jpg" border="0" alt="Jiné terény"></a>
		</td>
	</tr>
</table>