<?php
$this->title = 'Vysoké Tatry';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td>
			<?= $this->article->getArticleHTML(50);	?>
			<tr>
				<td>
					<hr>
				</td>
			</tr>
			<?= $this->article->getArticleHTML(60);	?>
			<tr>
				<td>
					<hr>
				</td>
			</tr>
			<?= $this->article->getArticleHTML(64);	?>
		</td>
	</tr>
</table>
