<?php
$this->title = 'Ropice';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td align="center">
			<h3>Jelikož pocházíme z vesnic pod malými horami Beskydy, jezdíme nejčastěji v Beskydech a to z 80% kolem sjezdovky ve vesnici s trochu matoucím názvem Řeka.</h3> 
			<table>
				<tr>
					<td>
						Nad údolím této vesnice se tyčí hora Ropice (1080 m.n.m) se svým severním svahem, který se pro nás za těch 6 let co na ní chodíme lyžovat stala kultovní.
					</td>
					<td>					
						<a href="javascript:closeWindow();openWindow1('/ropice/roppic01.php',716,330)"><img src='../images/ropice/rop18.jpg' border='0' alt='Pohled z protějšího kopce'></a>
						<?php
//						echo imgwin("$HOME/ropice/roppic01.php","$HOME/images/ropice/ropop.jpg","$HOME/images/ropice/rop18.jpg","Pohled z protějšího kopce");
						?>
					</td>
				</tr>
			</table>
			<?= $this->article->getArticleHTML(47);	?>
			
			<tr>
				<td>
					<hr>
				</td>
			</tr>
			<?= $this->article->getArticleHTML(58);	?>
			<tr>
				<td>
					<hr>
				</td>
			</tr>
			<?= $this->article->getArticleHTML(51);	?>
			<tr>
				<td>
					<hr>
				</td>
			</tr>
			<?= $this->article->getArticleHTML(52);	?>
		</td>
	</tr>
</table>
