<?php
$this->title = 'Lysá hora';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>

	<tr>
		<td align="left">

	<tr>
		<td align="center">
			<p align="left"><b>Vysoké Tatry</b> mají pro nás tu výhodu, že jsou poměrně blízko našeho bydliště. Nejsou zde žádné vleky, které by vás dovezly nahoru na místa volného lyžování takže to musíte poctivě vylézt sami. Typické lyžování je zde ve žlebech, kde se dá zažít spousta nejrůznějších situací.</p>
		</td>
	</tr>
	<tr>
		<td>
			<?php /*
			  echo "<tr><td><hr></td></tr>";
			  $id=45;
			  include("../clcore.php");
			  echo "<tr><td><hr></td></tr>";
			  $id=54;
			  include("../clcore.php");
			  echo "<tr><td><hr></td></tr>";
			  $id=55;
			  include("../clcore.php");
			  echo "<tr><td><hr></td></tr>";
			  $id=56;
			  include("../clcore.php");
			 */ ?>	

		</td>
	</tr>
</table>
