<?php
$this->title = 'chata pod lavinou';
$this->headTitle($this->title);
if ($this->isLogged) {
	$this->renderToPlaceholder('showport.phtml', 'showport');
	$this->renderToPlaceholder('comment.phtml', 'comment');
} else {
	$this->renderToPlaceholder('loginbox.phtml', 'loginbox');
}
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td valign="top" align="center" colspan="2">
			<font size="5" color="#777777"><b>chata pod lavinou</b></font><br>
			<font size="1" color="#999999">zatím ve zkušebním provozu, takže omluvte nějaké chyby jestli tu budou</font>
		</td>
	</tr>

	<?php if ($this->isLogged) { ?>
		<tr>
			<td valign="top">
				<?= $this->placeholder('comment') ?>
			</td>
		</tr>
	<?php } ?>

	<?php if ($this->newPost) { ?>
		<tr>
			<td>
				<a href="<?= $this->baseUrl() ?>/chat/posta"><img src="<?= $this->baseUrl() ?>/images/page/posta.gif"></a>
			</td>
		</tr>
	<?php } ?>

	<tr>
		<td width="100%">
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td>
						<hr width=100%>
					</td>
				</tr>
				<tr>
					<td>
						<b>
							<?= $this->paginator?>
							<?php if ($this->isLogged) { ?>
								<a href="'.$HOME.'/chat/index.php?'.$sex.'">Pošta</a>
								<? } ?>
								<a href="<?= $this->baseUrl() ?>/chat">Obsah</a>
							</b>
						</td>
					</tr>
					<tr>
						<td>
							<hr width=100%>
						</td>
					</tr>

					<?php
					foreach ($this->chatChata as $comment) {
						$author = $comment['user'];
						?>
						<tr>
							<td bgcolor='white'>
								<?php if ($this->isLogged) { ?>
									<a href="'.$HOME.'/chat/index.php?'.$sex.'">
										<? } ?>
										<img src="<?= $this->baseUrl() ?>/images/ports/<?= $comment['pic'] ?>" width='40' height='50' border='1' align='left'>
										<?php if ($this->isLogged) { ?>
										</a>
										<? } ?>
										<div align='left'><font color='black'> <b><?= $author ?></b>,&nbsp;
											<span class='pokecdat'><?= $comment['datum'] ?> <?= $comment['cas'] ?></span></div>
										<div class=mno><?= $comment['txt'] ?></div>
									</td>
								</tr>
								<tr>
									<td bgcolor='white'>
										<hr width=100%>
									</td>
								</tr>
								<?php
							}
							?>
							<tr>
								<td>
									<hr width=100%>
								</td>
							</tr>
							<tr>
								<td>
									<b>
										<?= $this->paginator?>
										<?php if ($this->isLogged) { ?>
											<a href="'.$HOME.'/chat/index.php?'.$sex.'">Pošta</a>
										<? } ?>
											<a href="<?= $this->baseUrl() ?>/chat">Obsah</a>
						</b>
					</td>
				</tr>
				<tr>
					<td>
						<hr width=100%>
					</td>
				</tr>

			</table>
		</td>
	<div>
		
	</div>
		<td valign='top'>
			<?= $this->isLogged ? $this->placeholder('showport') : $this->placeholder('loginbox')?>
		</td>
	</tr>

	<tr>
		<td align="center" valign=bottom colspan=3>
			<p>Čaute všichni freerideři a freeriderky. Všechny dotazy, připomínky a hlavně popis chyb směřujte na <a href="mailto:banix@centrum.cz">banix@centrum.cz</a>.</p>
		</td>
	</tr>
</table>