<?php
$this->title = 'chata pod lavinou';
$this->headTitle($this->title);
$npost = FALSE;
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td valign="top" align="center" colspan="2">
			<font size="5" color="#777777"><b>chata pod lavinou</b></font><br>
			<font size="1" color="#999999">zatím ve zkušebním provozu, takže omluvte nějaké chyby jestli tu budou</font>
		</td>
	</tr>
	<?php if ($npost) { ?>
	<tr>
		<td>
			<a href="/chat/posta.php"><img src="../images/page/posta.gif"></a>
		</td>
	</tr>
	<?php } ?>
	
	<tr>
		<td width="100%">
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td>
						<hr width=100%>
					</td>
				</tr>
				<tr>
					<td>
						<b>
							<a href="'.$PHP_SELF.'?'.$sex.'&offs=0">Nejnovější</a>&nbsp;&nbsp;
							<a href="'.$PHP_SELF.'?'.$sex.'&offs='.$noffs.'">Novější</a>&nbsp;&nbsp;
							<a href="'.$PHP_SELF.'?'.$sex.'&offs='.$poffs.'">Starší</a>&nbsp;&nbsp;
							<a href="'.$PHP_SELF.'?'.$sex.'&offs='.$counts.'">Nejstarší</a>&nbsp;&nbsp;
							<?php if ($this->isLogged) { ?>
								<a href="'.$HOME.'/chat/index.php?'.$sex.'">Pošta</a>
							<? } ?>
							<a href="'.$HOME.'/chat/index.php?'.$sex.'">Obsah</a>
						</b>
					</td>
				</tr>
				<tr>
					<td>
						<hr width=100%>
					</td>
				</tr>

				<?php
				foreach ($this->chatChata as $comment) {
					$author = $comment['user'];
					?>
					<tr>
						<td bgcolor='white'>
							<div align='left'><font color='black'> <b><?= $author ?></b>,&nbsp;
								<span class='pokecdat'><?= $comment['datum'] ?> <?= $comment['cas'] ?></span></div>
							<div class=mno><?= $comment['txt'] ?></div>
						</td>
					</tr>
					<?php
					//var_dump($comment);
					?>
					<tr>
						<td bgcolor='white'>
							<hr width=100%>
						</td>
					</tr>
					<?php
				}
				?>
				<tr>
					<td>
						<b>
							<a href="'.$PHP_SELF.'?'.$sex.'&offs=0">Nejnovější</a>&nbsp&nbsp
							<a href="'.$PHP_SELF.'?'.$sex.'&offs='.$noffs.'">Novější</a>&nbsp&nbsp
							<a href="'.$PHP_SELF.'?'.$sex.'&offs='.$poffs.'">Starší</a>&nbsp&nbsp
							<a href="'.$PHP_SELF.'?'.$sex.'&offs='.$counts.'">Nejstarší</a>&nbsp&nbsp
							<?php if ($this->isLogged) { ?>
								<a href="'.$HOME.'/chat/index.php?'.$sex.'">Pošta</a>
							<? } ?>
							<a href="'.$HOME.'/chat/index.php?'.$sex.'">Obsah</a>
						</b>
					</td>
				</tr>
				<tr>
					<td>
						<hr width=100%>
					</td>
				</tr>

			</table>
		</td>
		<td valign='top'>
			<h3>Loginbox/Portrait</h3>

		</td>
	</tr>

	<tr>
		<td align="center" valign=bottom colspan=3>
			<p>Čaute všichni freerideři a freeriderky. Všechny dotazy, připomínky a hlavně popis chyb směřujte na <a href=mailto:banix@centrum.cz> banix@centrum.cz</a>.</p>
		</td>
	</tr>
</table>