<?php
$this->title = 'freeridový pokec';
$this->headTitle($this->title);

?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td valign="top" align="center" colspan="2">
			<font size="5" color="#777777"><b>freeridový pokec</b></font><br>
			<font size="1" color="#999999">zatím ve zkušebním provozu, takže omluvte nějaké chyby jestli tu budou</font>
		</td>
	</tr>
	<tr>
		<td width="70%" align=center valign=top>
			<table cellpadding=4 cellspacing=7 width=100% border=0>
				<tr>
					<td align="center" valign="top">
						<font size="4"><b><a href="<?=$this->baseUrl()?>/chat/chata">Chata pod lavinou </a></b></font><br>
						<font color="#aaaaaa" size="2" >O všem, i o ničem :-)<br><strong><?=$this->lastChata['user']?></strong>&nbsp;&nbsp;<?=$this->lastChata['datum']?>&nbsp;<?=$this->lastChata['cas']?></font>
					</td>
					<td align="center" valign="top">
						<font size="4"><b><a href="<?=$this->baseUrl()?>/chat/event">Akce, setkání</a></b></font><br>
						<font color="#aaaaaa" size="2"><strong><?=$this->lastAction['user']?></strong>&nbsp;&nbsp;<?=$this->lastAction['datum']?>&nbsp;<?=$this->lastAction['cas']?></font>
					</td>
				</tr>
				<tr>
					<td align="center" valign="top">
						<font size="4"><b><a href="<?=$this->baseUrl()?>/chat/ride">Zážitky, rady, ...</a></b></font><br>
						<font color="#aaaaaa" size="2" >o sněhových (nejen) dobrobružstvích<br><strong><?=$this->lastRide['user']?></strong>&nbsp;&nbsp;<?=$this->lastRide['datum']?>&nbsp;<?=$this->lastRide['cas']?></font>
					</td>
					<td align="center" valign="top">
						<font size="4"><b><a href="<?=$this->baseUrl()?>/chat/regnew">Přidat nového uživatele</a></b><br></font>
						<font color="#aaaaaa" size="2" >Kdo se nezaregistruje, může jen číst</font>
					</td>
				</tr>
				<tr>
					<td align="center" valign="top">
						<font size="4"><b><a href="<?=$this->baseUrl()?>/chat/try">Zkušební pokec </a></b></font><br>
						<font color="#aaaaaa" size="2" >Cestina, HTML, ...<br><strong><?=$this->lastTry['user']?></strong>&nbsp;&nbsp;<?=$this->lastTry['datum']?>&nbsp;<?=$this->lastTry['cas']?></font>
					</td>
					<td align="center" valign="top">
						<font size="4"><b><a href="<?=$this->baseUrl()?>/chat/bazar">Bazar</a></b></font><br>
						<font color="#aaaaaa" size="2" >Prodej, koupě, výměna<br><strong><?=$this->lastBazar['user']?></strong>&nbsp;&nbsp;<?=$this->lastBazar['datum']?>&nbsp;<?=$this->lastBazar['cas']?></font>
					</td>
				</tr>
			</table>
		</td>
		<td width="30%" align="center" valign=top>
			<form action="?fsXID=" method="POST">
				<table align="right" border="4" cellpadding="3" cellspacing="2" bordercolorlight="silver" bordercolordark="gray">
					<tr>
						<td align="center">
						</td>
					</tr>
					<tr>
						<td>
							<table align="center" border="0" cellpadding="0" cellspacing="0">
								<tr>
									<td>
										<font face=courier color=gold> Uživatel:</font>
									</td>
									<td>
										<input type="Text" name="auser" value="" size="12">
									</td>
								</tr>
								<tr>
									<td>
										<font face=courier color=gold> Heslo:</font>
									</td>
									<td>
										<input type="Password" name="apass" size="12">
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td align="center">
							<input type="Submit" value="Přihlásit se">
						</td>
					</tr>
				</table>
			</form>
		</td>
	</tr>
	<tr>
		<td align="center" valign=bottom colspan=3>
			<p>Čaute všichni freerideři a freeriderky. Všechny dotazy, připomínky a hlavně popis chyb směřujte na <a href=mailto:banix@centrum.cz> banix@centrum.cz</a>.</p>
		</td>
	</tr>
</table>