<!DOCTYPE html>

<html>
	<head><title>Ultra Fun | banixname</title>
		<meta charset="UTF-8">
		<link rel='StyleSheet' href='css/fxski.css'>	
	</head>
	<body  marginwidth='0' marginheight='0' topmargin='0' link='#6655aa' vlink='#7777ee' alink='#ccffcc'>
		<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
			<tr>
				<td align=center height='98' valign='top' colspan='2'>
					<a href="index">
						<img src='images/page/title1.jpg' width='500' height='98'>
					</a>
				</td>
			</tr>

			<tr>
				<td align='center'>
					<h3>Dirt</h3>
				</td>
			</tr>
			<tr>
				<td align='left'>
					Proto?e nejezd?me jen na ly??ch, ale t?eba i na mtb tak tu je p?r fotek jak to asi vypadalo na podzim 2000.<br />
					M?sto: kupa hl?ny kdesi ve St??te?i.
				</td>
			</tr>
			<tr>
				<td align='center'>
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=185&dire=bike',607,460)"><img src='/clanky/bike/thumb/dirt01.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=186&dire=bike',609,460)"><img src='/clanky/bike/thumb/dirt02.jpg' border='0' alt='jura'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=187&dire=bike',565,460)"><img src='/clanky/bike/thumb/dirt03.jpg' border='0' alt='ja'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=188&dire=bike',521,460)"><img src='/clanky/bike/thumb/dirt04.jpg' border='0' alt=''></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=189&dire=bike',598,460)"><img src='/clanky/bike/thumb/dirt06.jpg' border='0' alt='ja'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=190&dire=bike',541,460)"><img src='/clanky/bike/thumb/dirt07.jpg' border='0' alt='radikus'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=191&dire=bike',511,460)"><img src='/clanky/bike/thumb/dirt08.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=192&dire=bike',605,460)"><img src='/clanky/bike/thumb/dirt09.jpg' border='0' alt='radikus'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=194&dire=bike',607,460)"><img src='/clanky/bike/thumb/dirt11.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=195&dire=bike',581,460)"><img src='/clanky/bike/thumb/dirt12.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=196&dire=bike',609,460)"><img src='/clanky/bike/thumb/dirt13.jpg' border='0' alt='j'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=197&dire=bike',605,460)"><img src='/clanky/bike/thumb/dirt14.jpg' border='0' alt='radikus'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=198&dire=bike',553,460)"><img src='/clanky/bike/thumb/dirt15.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=199&dire=bike',602,460)"><img src='/clanky/bike/thumb/dirt16.jpg' border='0' alt='radikus'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=200&dire=bike',710,460)"><img src='/clanky/bike/thumb/dirt17.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=201&dire=bike',593,460)"><img src='/clanky/bike/thumb/dirt18.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=202&dire=bike',553,460)"><img src='/clanky/bike/thumb/dirt19.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=203&dire=bike',510,460)"><img src='/clanky/bike/thumb/dirt20.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=204&dire=bike',631,460)"><img src='/clanky/bike/thumb/dirt21.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=205&dire=bike',608,460)"><img src='/clanky/bike/thumb/dirt22.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=206&dire=bike',674,460)"><img src='/clanky/bike/thumb/dirt24.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=207&dire=bike',611,460)"><img src='/clanky/bike/thumb/dirt25.jpg' border='0' alt='radikus'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=208&dire=bike',416,460)"><img src='/clanky/bike/thumb/dirt10.jpg' border='0' alt='jura'></a> 
				</td>
			</tr>
			<tr>
				<td align='right'>
					<a href='mailto:banix@centrum.cz'>-b-n-x-</a>
				</td>
			</tr>
			<tr>
				<td><hr></td>
			</tr>
			<tr>
				<td align='center'>
					<h3>Airs on Zlatnik</h3>
				</td>
			</tr>
			<tr>
				<td align='left'>Zlatn?k je mal? sjezdovka pod Lysou sm?rem na Visalaje. SnowBor??ci si tu postavili pjeknou sko?ku pro svoje z?vody a Robin s Romanem toho vyu?ili.</td>
			</tr>
			<tr>
				<td align='center'>
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=209&dire=airs',316,337)"><img src='/clanky/airs/thumb/zlatic01.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=210&dire=airs',416,348)"><img src='/clanky/airs/thumb/zlatic02.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=211&dire=airs',466,355)"><img src='/clanky/airs/thumb/zlatic03.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=212&dire=airs',466,411)"><img src='/clanky/airs/thumb/zlatic04.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=214&dire=airs',416,332)"><img src='/clanky/airs/thumb/zlatic06.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=215&dire=airs',466,337)"><img src='/clanky/airs/thumb/zlatic07.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=216&dire=airs',516,389)"><img src='/clanky/airs/thumb/zlatic08.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=217&dire=airs',366,414)"><img src='/clanky/airs/thumb/zlatic09.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=218&dire=airs',343,408)"><img src='/clanky/airs/thumb/zlatic10.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=219&dire=airs',516,427)"><img src='/clanky/airs/thumb/zlatic11.jpg' border='0' alt='robin mctwist'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=220&dire=airs',396,421)"><img src='/clanky/airs/thumb/zlatic12.jpg' border='0' alt='roman tailgrab'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=221&dire=airs',466,362)"><img src='/clanky/airs/thumb/zlatic13.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=222&dire=airs',496,436)"><img src='/clanky/airs/thumb/zlatic14.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=223&dire=airs',466,413)"><img src='/clanky/airs/thumb/zlatic15.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=224&dire=airs',516,386)"><img src='/clanky/airs/thumb/zlatic16.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=225&dire=airs',466,346)"><img src='/clanky/airs/thumb/zlatic17.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=226&dire=airs',466,411)"><img src='/clanky/airs/thumb/zlatic05.jpg' border='0' alt='robin'></a> 
				</td>
			</tr>
			<tr>
				<td align='right'>
					<a href='mailto:banix@centrum.cz'>-b-n-x-</a>
				</td>
			</tr>
			<tr>
				<td><hr></td>
			</tr>
			<tr>
				<td align='center'>
					<h3>Grass Skiing</h3>
				</td>
			</tr>
			<tr>
				<td align='left'>Zima 1997/1998 m?la fakt super ?nor. V noci plus 10?C, po sn?hu ani pam?tka. Na bajku sme akor?d jezdili, ale stejn? n?s to nemohlo uspokojit, tak?e nakonec na ly?e p?ece jen do?lo. Pro ty co nejsou skaln? ly?a?i to asi bude vypadat, jako bychom se trochu pom?tli, no ale co, tato zima taky nebyla norm?ln</td>
			</tr>
			<tr>
				<td align='center'>
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=227&dire=grass',469,370)"><img src='/clanky/grass/thumb/tric01.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=228&dire=grass',456,370)"><img src='/clanky/grass/thumb/tric02.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=229&dire=grass',518,370)"><img src='/clanky/grass/thumb/tric03.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=230&dire=grass',395,370)"><img src='/clanky/grass/thumb/tric04.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=231&dire=grass',455,370)"><img src='/clanky/grass/thumb/tric05.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=232&dire=grass',370,560)"><img src='/clanky/grass/thumb/tric09.jpg' border='0' alt='robin'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=233&dire=grass',324,510)"><img src='/clanky/grass/thumb/trrop02.jpg' border='0' alt='roman'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=234&dire=grass',235,370)"><img src='/clanky/grass/thumb/tric06.jpg' border='0' alt='halda'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=235&dire=grass',423,370)"><img src='/clanky/grass/thumb/tric07.jpg' border='0' alt='vrbice'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=236&dire=grass',466,418)"><img src='/clanky/grass/thumb/vrb01.jpg' border='0' alt='vrbice'></a> 
					<a href="javascript:closeWindow();openWindow1('/picone.php?id=237&dire=grass',466,370)"><img src='/clanky/grass/thumb/xsad1.jpg' border='0' alt='matterhorn'></a> 
				</td>
			</tr>
			<tr>
				<td align='right'>
					<a href='mailto:banix@centrum.cz'>-b-n-x-</a>
				</td>
			</tr>
		</table>
	</body>
</html>
