<!DOCTYPE html>

<html>
	<head><title> o nás | banixname</title>
		<meta charset="UTF-8">
		<link rel='StyleSheet' href='css/fxski.css'>	
	</head>
	<body  marginwidth='0' marginheight='0' topmargin='0' link='#6655aa' vlink='#7777ee' alink='#ccffcc'>
		<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
			<tr>
				<td align=center height='98' valign='top' colspan='2'>
					<a href="index">
						<img src='images/page/title1.jpg' width='500' height='98'>
					</a>
				</td>
			</tr>
			<tr>
				<td align="left">
					Tu se můžeš dozvědět něco o nás, co tuto stránku připravujeme. Časem tu asi přibudou další lidi.
				</td>
			</tr>
			<tr>
				<td align="center">
					<a href="aboutus/ja"><img src="images/page/ja_m.jpg" height="80" border="0" alt="já"></a>
					<a href="aboutus/robin"><img src="images/page/robin_m.jpg" height="80" border="0" alt="Robin"></a>
					<a href="aboutus/roman"><img src="images/page/roman_m.jpg" height="80" border="0" alt="Roman"></a><br>
				</td></tr>
			<tr>
				<td align="center">
					<p> Chceš-li o nás vědět víc klepni si na nějakou fotku.</p>
				</td>
			</tr>
		</table>
	</body>
</html>
