<!DOCTYPE html>

<html>
	<head><title>banixname | o nás</title>
		<meta charset="UTF-8">
		<link rel='StyleSheet' href='css/fxski.css'>	
	</head>
	<body  marginwidth='0' marginheight='0' topmargin='0' link='#6655aa' vlink='#7777ee' alink='#ccffcc'>
		<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
			<tr><td align=center height='98' valign='top' colspan='2'>
					<img src='images/page/title1.jpg' width='500' height='98'>
				</td></tr>	<tr><td align="left">
					Tu se můžeš dozvědět něco o nás, co tuto stránku připravujeme. Časem tu asi přibudou další lidi.
				</td></tr>
			<tr><td align="center">
					<a href="/we/ja.php"><img src="images/page/ja_m.jpg" height="80" border="0" alt="já"></a>
					<a href="/we/robin.php"><img src="images/page/robin_m.jpg" height="80" border="0" alt="Robin"></a>
					<a href="/we/roman.php"><img src="images/page/roman_m.jpg" height="80" border="0" alt="Roman"></a><br>
				</td></tr>
			<tr><td align="center">
					<P> Chceš-li o nás vědět víc klepni si na nějakou fotku.
						<a href="index/"><img src="images/page/home.gif" width="122" height="45" align="right" border="0" alt="domů"></a>
				</td></tr>
		</table>
	</body>
</html>
