<?php
$this->title = 'Petr Šlachta';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>


	<tr>
		<td align="center">
			<img src="<?= $this->baseUrl() ?>/images/page/ja.jpg" width="345" height="268" align="right" border="4">
			<p align="left">
				Takže to jsem já. Možná se ptáte co dělá beznohý invalida v horách. Jenže já nohy naštěstí mám (obě), a to že nejdou vidět je tím, že po dojezdu (dokutálení :-) mě přisypala drobná lavinka, jak vidíte na fotce. <br> 
				Jinak se o mě dá říct, že rád lyžuju, bikuju, lezu (víc padám), ležím, spím, atd... Na lyžích jsem si vybil 2 zrovna vyrostlé druhé zuby, dvakrát jsem měl nohu v sádře a jednou jsem vjel pod auto (to jsem byl ale moc malý, bo jsem se tam vešel). <br>
				No a jmenuju se Petr 'BANÍK' Šlachta a jsem ze skoropodbeskydské dědiny Střítež u Českého Těšína (až to něgdy budete vyslovovat tak neříkejte Střítěž s "ě". Střítežské nacionalisty to dost štve). <br>
				No a víc o sobě fakt neřeknu, protože to je utajovaná skutečnost.</p><br>
		</td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table border=0 cellpadding="1" cellspacing="1" align="left">
				<tr>
					<td align=left valign=top><b>Co štastně vlastním:</b></td>
					<td align=left>
						<img src="<?= $this->baseUrl() ?>/images/page/candide.jpg" width="400" height="64"><br>
						<img src="<?= $this->baseUrl() ?>/images/page/intoxica.jpg" width="400" height="43"><br>
						<img src="<?= $this->baseUrl() ?>/images/page/bigkahuna.jpg" width="400" height="51"><br>
						<img src="<?= $this->baseUrl() ?>/images/page/xwave8.gif" width="142" height="112">
						<img src="<?= $this->baseUrl() ?>/images/page/langeboot.gif" width="97" height="110">
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table border=0 cellpadding="1" cellspacing="1" align="left">
				<tr>
					<td align=left valign=top><b>Zničené či poškozené lyže:</b></td>
					<td width="50%">Už to tady nebudu psát, bo je toho hodně (vjetšinou prošláplé a prakticky bez skluznice)<br>
				</tr>
			</table>
		</td>
	</tr>


	
	
</table>