<?php
$this->title = 'Robin Kaleta';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td align="center">
			<img src="<?= $this->baseUrl() ?>/images/page/robin.jpg" align="left" border="4">
			<p align="left">
				Tž, tu ten synek se jmenuje Robin Kaleta. Z nás co tu jsme dělá asi největší vychytávky. Po psychické stránce je připraven úplně sqěle. Přijede třeba nad skálu, (já bych přemýšlel ještě pár dnů jestli by ji něgdo ze světových extrémistů skočil) podívá se trochu dolů a hópne. Zatím se mu ještě nic vážného na lyžích nestalo, doufejme, že to tak zůstane.<br> 
				Jinak taky mountainbajkuje, leze, skáče do všeho, a mimo dalších asi 20 sportů i závodně tancuje klasické tance. V tomto oboru je spolu se svou sestrou jedním z nejlepších u nás. Bydlí taky ve Stříteži jako já.</p><br>
		</td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table border=0 cellpadding="1" cellspacing="1">
				<tr>
					<td align=left valign=top><b>Aktuální výbava:</b></td>
					<td align=left>
						<IMG SRC="<?= $this->baseUrl() ?>/images/page/supermountain.jpg"><br>
						<IMG SRC="<?= $this->baseUrl() ?>/images/page/enemy.gif">
						<br><IMG SRC="<?= $this->baseUrl() ?>/images/page/s912.gif">
						<IMG SRC="<?= $this->baseUrl() ?>/images/page/xwave8.gif">
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table border=0 cellpadding="1" cellspacing="1" align="left">
				<tr>
					<td align=left valign=top><b>Zničené či poškozené lyže:</b></td>
					<td align=left>K2 Enemy 01/02 (zlomená)<br>
						K2 Enemy 00/01 (zlomená)<br>
						Kastle Aerospeed 7.0 (ohnutá a urvaná hrana)<br>
						K2 ProCarve (utržená hrana)<br>
						Kastle TCX (zlomená)<br>
						Rossignol (utržené hrany)</td>
				</tr>
			</table>
		</td>
	</tr>

	
	
</table>