<?php
$this->title = 'Roman Heczko';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>

	<tr>
		<td align="center">
			<img src="<?=$this->baseUrl()?>/images/page/roman.jpg" align="right" border="4">
			<p align="left">
				No, a toto je Roman Heczko. Ten když jsem si myslel, že za námi bude zaostávat, tak skočil jako první z nás 360. Zatím je jeho nejdrsnějším zážitkem sjezd jednoho hodně prudkého, ledového žlebu v Tatrách, po zádech hlavou dolů s následným spadnutím do skalní asi 4 m hluboké průrvy. Odneslo to hlavně vázání a jeho (Romanova) zadní část těla. Naštěstí nedošlo k trvalým následkům. Ani fyzickým, ani psychiatrickým. Už zase jezdí i žleby.<br>
				Na rozdíl od nás (já a Robin) nebydlí ve Stříteži, ale v sousední vesnici Hnojníku.</p><br>

		</td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table border=0 cellpadding="1" cellspacing="1" align="left">
				<tr>
					<td align=left valign=top width="130"><b>Aktuální výbava:</b></td>
					<td>
						<IMG SRC="<?=$this->baseUrl()?>/images/page/supermountain.jpg">
						<IMG SRC="<?=$this->baseUrl()?>/images/page/enemy.gif">
						<br><IMG SRC="<?=$this->baseUrl()?>/images/page/s912.gif">
						<IMG SRC="<?=$this->baseUrl()?>/images/page/xscreemboot.gif">
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="left" valign="top">
			<table border=0 cellpadding="1" cellspacing="1" align="left">
				<tr>
					<td align=left valign=top><b>Zničené či poškozené lyže:</b></td>
					<td align=left>K2 Enemy 00/01 (zlomená)<br>	
						Atomic MegaCarve (obě dvě podélně zlomeny při hranách)<br>
						Kneissl (zlomená)</td>
				</tr>
			</table>
		</td>
	</tr>

</table>