<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' | ');
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle('BanixName');

echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php
		echo $this->headLink()
				->prependStylesheet($this->baseUrl() . '/css/fxski.css');
		?>
		<!--<script src="<?= $this->baseUrl() ?>/js/script.js"></script>-->
		<SCRIPT LANGUAGE="JavaScript">

	var popUpWin
	var isIE3
	var isIE3 = (navigator.appVersion.indexOf("MSIE 3") != -1) ? true : false
	
	function openWindow(url) {
			popUpWin = window.open(url,"gallery","toolbar=no,location=0,directories=0,status=no,menubar=no,scrollbars=yes,resizable=yes,width=460,height=365,top=30,left=190");
	
			if (popUpWin.opener == null) {
			popUpWin.opener = window
		}
	
		if (navigator.appName == 'Netscape') {
			popUpWin.focus();
	
			}
	}
        	
	function openWindow1(url,sir,vys) {
		head = "toolbar=no,location=0,directories=0,status=no,menubar=no,scrollbars=yes,resizable=yes,width="+sir+",height="+vys+",top=30,left=190";
			popUpWin = window.open(url,"gallery",head);
	
			if (popUpWin.opener == null) {
			popUpWin.opener = window
		}
	
		if (navigator.appName == 'Netscape') {
			popUpWin.focus();
	
			}
	}
        	
	function openWindow2(url) {
			popUpWin = window.open(url,"gallery2","toolbar=no,location=0,directories=0,status=no,menubar=no,scrollbars=yes,resizable=yes,width=460,height=540,top=40,left=190");
	
			if (popUpWin.opener == null) {
			popUpWin.opener = window
		}
	
		if (navigator.appName == 'Netscape') {
			popUpWin.focus();
	
			}
        	
	}
	
	function closeWindow() {
	
		if (isIE3) {
			popUpWin = window.open("/blank.html","gallery","toolbar=no,location=0,directories=0,status=no,menubar=no,scrollbars=yes,resizable=no,height=1,width=1")
		}
		
		if (popUpWin && !popUpWin.closed) {
			popUpWin.close()
		}
		popUpWin = ""
	}	
	
		</SCRIPT>
	</head>
	<body>
		<div id="header">
			<a href="<?= $this->baseUrl() ?>/index" title="HOMEPAGE"></a>
		</div>
		<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-55941512-2', 'auto');
	  ga('send', 'pageview');

		</script>
		<div id="content">
			<!--<h1><?php echo $this->escape($this->title); ?></h1>-->
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>