<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' | ');
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle('BanixName');

echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php
		echo $this->headLink()
				->prependStylesheet($this->baseUrl() . '/css/fxski.css');
		?>
		<script src="<?= $this->baseUrl() ?>/js/script.js"></script>
	</head>
	<body>
		<div id="header">
			<a href="<?= $this->baseUrl() ?>/index" title="HOMEPAGE"></a>
		</div>
		<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-55941512-2', 'auto');
	  ga('send', 'pageview');

		</script>
		<div id="content">
			<!--<h1><?php echo $this->escape($this->title); ?></h1>-->
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>