<?php
$this->title = 'Video';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td align="center">
			<p>Tyto novější videa jsou v DIVX avi, takže si stáhněte codek divx pokud jej ještě nemáte.<br><br>
				<a href="videos/chopocross.avi"><img src="images/videos/chopocross.gif" border="0" alt="Robinuv cross na Chopku"></a>
				<a href="videos/rh01ff.avi"><img src="images/videos/rh01.gif" border="0" alt="Romanuv frontflip"></a>
				<a href="videos/rk01r540.avi"><img src="images/videos/rk01.gif" border="0" alt="Robinové rodeo540"></a>
				<a href="videos/rk02fr540.avi"><img src="images/videos/rk02.gif" border="0" alt="Robinův pokus o fakie rodeo540"></a>
				<a href="videos/rk04mcjap.avi"><img src="images/videos/rk04.gif" border="0" alt="Robinův mctwist japan"></a>
				<a href="videos/tg01bff.avi"><img src="images/videos/tg01.gif" border="0" alt="Tomáš Guziur - fakie backflip fakie"></a>
				<a href="videos/tg02bf.avi"><img src="images/videos/tg02.gif" border="0" alt="Tomáš Guziur - cross backflip"></a>
			<p>Tak tu jsou nějaké starší videa. Všechny jsou v MPEGu, takže omluvte sníženou kvalitu záznamu.<br><br>
				<a href="videos/robai01.mpg"><img src="images/videos/robai01.jpg" border="0" alt="Robinův air"></a>
				<a href="videos/robbf01.mpg"><img src="images/videos/robbf01.jpg" border="0" alt="backflip"></a>
				<a href="videos/ban3601.mpg"><img src="images/videos/ban3601.jpg" border="0" alt="360°"></a>
				<a href="videos/rom3601.mpg"><img src="images/videos/rom3601.gif" border="0" alt="360°"></a>
				<a href="videos/robbf02.mpg"><img src="images/videos/robbf02.jpg" border="0" alt="backflip"></a>
				<a href="videos/robff01.mpg"><img src="images/videos/robff01.jpg" border="0" alt="frontflip"></a>
				<a href="videos/rom3602.mpg"><img src="images/videos/rom3602.jpg" border="0" alt="360°"></a>
				<a href="videos/rom3603.mpg"><img src="images/videos/rom3603.jpg" border="0" alt="360°"></a>
				<a href="videos/rom3604.mpg"><img src="images/videos/rom3604.jpg" border="0" alt="360°"></a>
				<a href="videos/rob3601.mpg"><img src="images/videos/rob3601.jpg" border="0" alt="360°"></a>
			<p>následující video zachycuje druhý Romanův pokus o backflipa. první skončil na jeho hlavě a kupodivu se mu nic nestalo. druhý pokus již tak šťastně neskončil. robinova přilba se mu zakousla nad horní ret a bylo z toho šití na chirurgicko - traumatologické ambulanci</p>
			<a href="videos/romcrash01.mpg"><img src="images/videos/romcrash01.jpg" border="0" alt="havarie"></a><br>
			<p>Video si samozřejmě stáhnete kliknutím na dotyčný obrázek znázorňující situaci.</p>
		</td>
	</tr>
</table>
