<?php
$this->title = 'Odkazy';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td align="center" valign=middle>
			<font size=+2><b> 
				<a href="links/personal">osobní stránky jiných riderů</A><br>
				<br><a href="links/magazines">časopisy</A><br>
				<br><a href="links/misc">různé</A><br>
				<br><a href="links/products">produkty</A><br>
			</b></font> <br>
		</td>
	</tr>
	<tr>
		<td align="center" valign=bottom> 
				<a href="http://www.skinet.com/" target="_blank"><img src="images/page/skinet.gif" border="0" alt="Server SkiNet"></a> 
				<a href="http://www.goski.com/" target="_blank"><img src="images/page/goski.gif" border="0" alt="Server GoSki"></a>
				<a href="http://www.skicentral.com/" target="_blank"><img src="images/page/scentral.gif" border="0" alt="Server SkiCentral"></a>
				<a href="http://www.skinet.cz/" target="_blank"><img src="images/page/skicz.gif" border="0" alt="Český Server SKI.CZ"></a></p>
		</td>
	</tr>
</table>
