<!DOCTYPE html>

<html>
	<head><title>odkazy | banixname</title>
		<meta charset="UTF-8">
		<link rel='StyleSheet' href='css/fxski.css'>	
	</head>

	<body  marginwidth='0' marginheight='0' topmargin='0' link='#6655aa' vlink='#7777ee' alink='#ccffcc'>
		<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
			<tr>
				<td align=center height='98' valign='top' colspan='2'>
					<a href="index">
						<img src='images/page/title1.jpg' width='500' height='98'>
					</a>
				</td>
			</tr>
			<tr>
				<td align="center" valign=middle>
					<font size=+2><b> 
						<a href="/links/links_person.php">osobní stránky jiných riderů</A><br>
						<br><a href="/links/links_mags.php">časopisy</A><br>
						<br><a href="/links/links_misc.php">různé</A><br>
						<br><a href="/links/links_prod.php">produkty</A><br>
					</b></font> <br>
				</td>
			</tr>
			<tr>
				<td align="center" valign=bottom> 
					<p><a href="http://www.skiin.com/"><img src="images/page/skiin.gif" border="0" alt="Server Ski In"></a>
						<a href="http://www.skinet.com/"><img src="images/page/skinet.gif" border="0" alt="Server SkiNet"></a> 
						<a href="http://www.goski.com/"><img src="images/page/goski.gif" border="0" alt="Server GoSki"></a>
						<a href="http://www.skicentral.com/"><img src="images/page/scentral.gif" border="0" alt="Server SkiCentral"></a>
						<a href="http://www.skinet.cz/"><img src="images/page/skicz.gif" border="0" alt="Český Server SKI.CZ"></a></p>
				</td>
			</tr>
		</table>
	</body>
</html>
