<?php
$this->title = 'Odkazy';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>

	<tr>
		<td>
			<table border="0" cellpadding=0 cellspacing=10>

				<tr>
					<td align=center valign="top" width="15%">
						<a href="http://www.fall-line.co.uk/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/fallogov.gif" border="0" alt="FallLine"></a>
					</td>
					<td align="left" valign="top" width="35%">
						<b>Anglický časopis</b></td>

					<td align="left" valign="top" width="15%">
						<a href="http://www.freeskier.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/freeskier.gif" border="0" alt="Freeskier"></a>
					</td>
					<td align="left" valign="top" width="35%">
						<b>o lyžování ve volném terénu.</b>
					</td>
				</tr>

				<tr>
					<td align=center width="15%">
						<a href="http://www.freezeonline.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/freeze.jpg" border="0" alt="Freeze"></a>
					</td>
					<td align="left" valign="top" width="35%">
						<b>Perfektní časák o nových směrech v lyžování.</b>
					</td>

					<td align="left" valign="top" width="15%">
						<a href="http://www.powdermag.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/pcover1.jpg" border="0" alt="Powder"></a>
					</td>
					<td align="left" valign="top" width="35%">
						<b>Asi nejlepší o lyžování ve volném terénu.</b>
					</td>
				</tr>

				<tr>
					<td align=center width="15%">
						<a href="http://www.skiingmag.com/" target="_blank"><IMG SRC="<?= $this->baseUrl() ?>/images/page/skiing.gif" border="0" alt="Skiing Magazine"></a>
					</td>
					<td align="left" valign="top" width="35%">
						<b>Normální lyžařský časopis. Dobré testy lyží, bot atd...</b>
					</td>

					<td align=center width="15%">
						<a href="http://www.skimag.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skimag.gif" border="0" alt="Ski Magazine"></a>
					</td>
					<td align="left" valign="top" width="35%">
						<b>Jako Skiing.</b>
					</td>
				</tr>

				<tr>
					<td align=center width="15%">
						<a href="http://www.skimagazin.cz/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skimagcz.gif" border="0" alt="Český Ski Magazín"></a>
					</td>
					<td align="left" valign="top" width="35%">
						<b>Český Skimagazín.</b>
					</td>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center" valign="bottom">
			<a href="http://www.goski.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/goski.gif" border="0" alt="Server GoSki"></a>
			<a href="http://www.skinet.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skinet.gif" border="0" alt="Server SkiNet"></a>
			<a href="http://www.skicentral.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/scentral.gif" border="0" alt="Server SkiCentral"></a>
			<a href="http://www.skinet.cz/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skicz.gif" border="0" alt="Český Server SKI.CZ"></a><br>
		</td>
	</tr>

</table>

