<?php
$this->title = 'Různé';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td>
			<table border=0 cellpadding=0 cellspacing=10>
				<tr>
					<td align=center>
						<a href="http://www.freeskiers.org/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/ifsa.gif" border="0" alt="IFSA"></A>
					</td>
					<td align=left valign=top>
						<b>Domovské stránky IFSA - International Free Skiing Asociation</b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.tetongravity.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/tgr.gif" border="0" alt="TGR"></A></td>
					<td align=left valign=top>
						<b>Teton gravity research - Filmaři filmující volné lyžování. (pár hezkých klipů)</b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.propage.cz/snowwave/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/snww.gif" border="0" alt="SnowWave"></A></td>
					<td align=left valign=top>
						<b>Perfektní české SNB stránky.</b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.skisports.cz" target="_blank">www.skisports.cz</A></td>
					<td align=left valign=top>
						<b>Lyžařské stránky Ivana Sosny</b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.mountainzone.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/mzone.gif" border="0" alt="Mountainzone"></a></td>
					<td align=left valign=top>
						<b>Rozsáhlý Web o všelijakých horských sportech</b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.freezefotoz.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/freezephotos.png" border="0" alt="FreezePhotos"></a></td>
					<td align=left valign=top>
						<b>Dost dobré fotky nejen lyžařské.</b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.sovaski.cz" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/sovaski.gif" border="0" alt="Sovaski"></a></td>
					<td align=left valign=top>
						<b>Stránky Bohumínského dovozce lyží a výbavy.</b>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center" valign=bottom>
			<a href="http://www.goski.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/goski.gif" border="0" alt="Server GoSki"></A>
			<a href="http://www.skinet.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skinet.gif" border="0" alt="Server SkiNet"></A>
			<a href="http://www.skicentral.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/scentral.gif" border="0" alt="Server SkiCentral"></a>
			<a href="http://www.skinet.cz/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skicz.gif" border="0" alt="Český Server SKI.CZ"></A><br>
		</td>
	</tr>
</table>
