<?php
$this->title = 'Osobní';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>
	<tr>
		<td>
			<table border=0 cellpadding=0 cellspacing=10>
				<tr>
					<td align=center>
						<a href="http://freeride.host.sk/" target="_blank">Miro Vich</A>
					</td>
					<td align=left valign=top>
						<b></b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.ekt.wz.cz/" target="_blank">Extreme Kotel Team</A>
					</td>
					<td align=left valign=top>
						<b>Znovuzrození :-)</b>&nbsp;
						<a href="http://iglobe.idnes.cz/igcechy.asp?r=igcechy&c=A010130_095028_igcechy_ch" target="_blank">tu je něco o nich :-)))</a>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://freeskiing.kgb.cz/" target="_blank">Honza Schauer</A>
					</td>
					<td align=left valign=top>
						<b></b>
					</td>
				</tr>
				<tr>
					<td align=center>
						<a href="http://www.sweb.cz/camir" target="_blank">Carlosovy stránky</A>
					</td>
					<td align=left valign=top>
						<b></b>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center" valign=bottom>
			<a href="http://www.goski.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/goski.gif" border="0" alt="Server GoSki"></A>
			<a href="http://www.skinet.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skinet.gif" border="0" alt="Server SkiNet"></A>
			<a href="http://www.skicentral.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/scentral.gif" border="0" alt="Server SkiCentral"></a>
			<a href="http://www.skinet.cz/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skicz.gif" border="0" alt="Český Server SKI.CZ"></A>
		</td>
	</tr>
</table>
