<?php
$this->title = 'Odkazy';
$this->headTitle($this->title);
?>
<table cellspacing='0' cellpadding='0' border='0' width='715' height='97%' align='center'>

	<tr>
		<td align="center">
			<a href="http://www.atomic.at/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/atomic.gif" border="0" alt="Atomic"></A>
			<a href="http://www.skisdynamic.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/dynamic.gif" border="0" alt="Dynamic"></A>
			<a href="http://www.dynastar.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/dynastar.gif" border="0" alt="Dynastar"></A>
			<a href="http://www.elanskis.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/elan.gif" border="0" alt="Elan"></A>
			<a href="http://www.fischer-ski.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/fischer.gif" border="0" alt="Fischer"></A>
			<a href="http://www.nordica.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/nordica.gif" border="0" alt="Nordica"></A>
			<a href="http://www.rossignol.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/rossi.gif" border="0" alt="Rossignol"></A>
			<a href="http://www.tecnicausa.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/technica.gif" border="0" alt="Technica"></A>
			<a href="http://www.salomonsports.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/salomon.gif" border="0" alt="Salomon"></A>
			<a href="http://www.scottusa.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/scott.gif" border="0" alt="Scott"></A>
			<a href="http://www.arnette.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/arnette.gif" border="0" alt="Arnette"></A>

			<a href="http://www.langeusa.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/lange.gif" border="0" alt="Lange"></A>
			<a href="http://www.volantski.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/volant2.gif" border="0" alt="Volant"></A>
			<a href="http://www.voelkl.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/voelkl.gif" border="0" alt="Völkl"></A>
			<a href="http://www.head.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/head.gif" border="0" alt="Head"></A>
			<a href="http://www.k2skis.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/k2.gif" border="0" alt="K2"></A>
			<a href="http://www.hartski.de/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/hart.gif" border="0" alt="Hart"></A>
			<a href="http://www.smithsport.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/smith.gif" border="0" alt="Smith"></A>
			<a href="http://www.bolle.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/bolle.gif" border="0" alt="Bollé"></A>
			<a href="http://www.burton.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/burton.gif" border="0" alt="Burton"></A>
			<a href="http://www.lineski.com" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/line.gif" border="0" alt="Line"></A>
		</td>
	</tr>
	<tr>
		<td align="center" valign=bottom>
			<a href="http://www.goski.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/goski.gif" border="0" alt="Server GoSki"></A>
			<a href="http://www.skinet.com/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skinet.gif" border="0" alt="Server SkiNet"></A>
			<a href="http://www.skinet.cz/" target="_blank"><img src="<?= $this->baseUrl() ?>/images/page/skicz.gif" border="0" alt="Český Server SKI.CZ"></A><br>
		</td>
	</tr>
</table>
